'''
Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, 
find the sum of the even-valued terms.
'''

import numpy as np

def find_fib_even_sum(limit):

    fib_list = [1,2]

    while (fib_list[-1] < limit):
        fib_list.append(fib_list[-2]+fib_list[-1])

    even_list = [x for x in fib_list if x % 2 == 0]

    # print(fib_list)
    # print(even_list)

    return sum(even_list)

result = find_fib_even_sum(4000000)

print(result)